
services:
  mongodb:
    image: mongo:latest
    container_name: journey-mongo
    ports:
      - "27017:27017"   # Exposes MongoDB on your local machine
    volumes:
      - ./data/mongo:/data/db  # Persist data locally

  redis:
    image: redis:latest
    container_name: journey-redis
    ports:
      - "6379:6379"   # Exposes Redis on your local machine
